project_id = "wzoeijpdtpysbkmxbcld"
[functions.generate-task-details]
enabled = true
verify_jwt = true
import_map = "./functions/generate-task-details/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-task-details/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-task-details/*.html" ]
